[package]
name = "struct-variant"
version = "0.1.0"
authors = ["Daniel Hrabovcak <thespiritxiii@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
itertools = "0.9.0"
proc-macro-error = "1.0.4"

[dependencies.syn]
version = "1.0.54"
features = ["full"]
